import chokidar from "chokidar";
import fs from "fs/promises";
import path from "path";

export type ProjectType = "react" | "next-app" | "next-page";

interface GenerateOptions {
  root: string;
  type: ProjectType;
  out: string;
  watch?: boolean;
}

/**
 * ✅ 라우트 루트 탐색
 */
async function resolveRootDir(base: string, type: ProjectType): Promise<string> {
  const candidates =
    type === "react"
      ? [path.join(base, "src")]
      : type === "next-app"
      ? [path.join(base, "app"), path.join(base, "src", "app")]
      : [path.join(base, "pages"), path.join(base, "src", "pages")];

  for (const c of candidates) {
    try {
      const stat = await fs.stat(c);
      if (stat.isDirectory()) return c;
    } catch {}
  }
  throw new Error(`❌ Could not find route root for ${type}`);
}

/**
 * ✅ 폴더 및 파일에서 라우트 경로를 추출 (트리 없이 flat)
 */
async function collectRoutes(
  dir: string,
  prefix = ""
): Promise<{ path: string; params: string[] }[]> {
  const result: { path: string; params: string[] }[] = [];

  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = entries.filter((e) => e.isFile());
  const dirs = entries.filter((e) => e.isDirectory());

  // ✅ 이 폴더에 page.tsx / index.tsx 존재 → route로 등록
  const hasPage = files.some((f) => /^(page|index)\.(t|j)sx?$/.test(f.name));
  if (hasPage) {
    result.push({ path: prefix || "/", params: extractParams(prefix) });
  }

  for (const entry of dirs) {
    const name = entry.name;

    // 🧩 __폴더 → 완전 무시
    if (name.startsWith("__")) continue;

    // 🧩 parallel route (@segment) → 무시
    if (name.startsWith("@")) continue;

    // 🧩 intercept route ( (..segment) ) → path에 영향 없음, 내부 탐색
    if (/^\(\.\..*\)$/.test(name)) {
      const subPath = path.join(dir, name);
      result.push(...(await collectRoutes(subPath, prefix)));
      continue;
    }

    // 🧩 group route ( (group) ) → path에는 포함하지 않지만 내부 탐색
    if (/^\(.*\)$/.test(name)) {
      const subPath = path.join(dir, name);
      result.push(...(await collectRoutes(subPath, prefix)));
      continue;
    }

    // 💥 Catch-all [...slug]
    if (/^\[\.\.\..*\]$/.test(name)) {
      const param = name.slice(4, -1);
      const newPrefix = `${prefix}/${"${string}"}`;
      const subDir = path.join(dir, name);
      result.push(...(await collectRoutes(subDir, newPrefix)));
      continue;
    }

    // 💥 Dynamic Route [id]
    if (/^\[.*\]$/.test(name)) {
      const param = name.slice(1, -1);
      const newPrefix = `${prefix}/$${param}`;
      const subDir = path.join(dir, name);
      result.push(...(await collectRoutes(subDir, newPrefix)));
      continue;
    }

    // ✅ 일반 폴더
    const safeSegment = name.replace(/-/g, "_"); // 하이픈 → 언더바
    const newPrefix = `${prefix}/${safeSegment}`;
    const subDir = path.join(dir, name);
    result.push(...(await collectRoutes(subDir, newPrefix)));
  }

  return result;
}

/**
 * ✅ path 문자열의 파라미터($id 등) 추출
 */
function extractParams(p: string): string[] {
  const matches = p.match(/\$\w+/g);
  return matches ? matches.map((p) => p.slice(1)) : [];
}

/**
 * ✅ 인터페이스 이름 안전 치환
 */
function makeInterfaceName(routePath: string): string {
  return (
    "Route_" +
    routePath
      .replace(/[\/:$]+/g, "_")
      .replace(/_+$/, "")
      .replace(/^_/, "")
      .replace(/\$\w+/g, (p) => p)
      .replace(/-/g, "_") // 하이픈 → 언더바
      .replace(/[^\w_]/g, "") // 나머지 특수문자 정리
  );
}

/**
 * ✅ 타입 파일 문자열 생성
 */
function makeTypeFile(routes: { path: string; params: string[] }[]): string {
  const routeTypes = routes
    .map((r) => {
      const interfaceName = makeInterfaceName(r.path);
      const params =
        r.params.length > 0
          ? `params: { ${r.params.map((p) => `${p}: string`).join("; ")} };`
          : "params?: never;";

      return `export interface ${interfaceName} {
  path: "${r.path}";
  ${params}
}`;
    })
    .join("\n\n");

  const union = routes.map((r) => makeInterfaceName(r.path)).join(" | ");

  return `// Auto-generated by safe-router
// Last updated: ${new Date().toISOString()}

${routeTypes}

export type AllRoutes = ${union};
`;
}

/**
 * ✅ 타입 파일 생성
 */
export async function generateTypeFile(options: GenerateOptions) {
  const { root, type, out, watch } = options;
  const routeRoot = await resolveRootDir(root, type);

  async function generate() {
    const routes = await collectRoutes(routeRoot);
    const fileContent = makeTypeFile(routes);

    await fs.mkdir(path.dirname(out), { recursive: true });
    await fs.writeFile(out, fileContent, "utf8");
    console.log(`✅ Routes generated: ${out}`);
  }

  await generate();

  if (watch) {
    console.log(`👀 Watching for route changes in ${routeRoot}`);
    chokidar.watch(routeRoot, { ignoreInitial: true }).on("all", generate);
  }
}
